//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autopartes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Autopartes()
        {
            this.Manten_Autopar = new HashSet<Manten_Autopar>();
        }
    
        public int IdAutopartes { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Cantidad_Total { get; set; }
        public Nullable<int> IdCategoriaAutoparte { get; set; }
        public Nullable<int> IdConcesinaria { get; set; }
    
        public virtual CategoriaAutoparte CategoriaAutoparte { get; set; }
        public virtual Concesinaria Concesinaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manten_Autopar> Manten_Autopar { get; set; }
    }
}
