//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Referencias = new HashSet<Referencias>();
            this.VentaAuto = new HashSet<VentaAuto>();
        }
    
        public int IdCliente { get; set; }
        public string Numero { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> FechaNac { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> TelCasa { get; set; }
        public Nullable<int> TelCel { get; set; }
        public string Correo { get; set; }
        public string RFC { get; set; }
        public Nullable<int> IdMunicipio { get; set; }
        public Nullable<int> IdEstado_Cliente { get; set; }
    
        public virtual Estado_Cliente Estado_Cliente { get; set; }
        public virtual Municipio Municipio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Referencias> Referencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaAuto> VentaAuto { get; set; }
    }
}
