//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionaria.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConcesionariaEntities : DbContext
    {
        public ConcesionariaEntities()
            : base("name=ConcesionariaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accesorio> Accesorio { get; set; }
        public virtual DbSet<AccesorioList> AccesorioList { get; set; }
        public virtual DbSet<Anios> Anios { get; set; }
        public virtual DbSet<AutoAccesorio> AutoAccesorio { get; set; }
        public virtual DbSet<AutoCliente> AutoCliente { get; set; }
        public virtual DbSet<AutoColorList> AutoColorList { get; set; }
        public virtual DbSet<AutoEstadoList> AutoEstadoList { get; set; }
        public virtual DbSet<AutoMarca> AutoMarca { get; set; }
        public virtual DbSet<AutoModelo> AutoModelo { get; set; }
        public virtual DbSet<Automovil> Automovil { get; set; }
        public virtual DbSet<Autopartes> Autopartes { get; set; }
        public virtual DbSet<CategoriaAutoparte> CategoriaAutoparte { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Concesinaria> Concesinaria { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Estado_Cliente> Estado_Cliente { get; set; }
        public virtual DbSet<Fabrica> Fabrica { get; set; }
        public virtual DbSet<Manten_Autopar> Manten_Autopar { get; set; }
        public virtual DbSet<MantenEstado> MantenEstado { get; set; }
        public virtual DbSet<Mantenimiento> Mantenimiento { get; set; }
        public virtual DbSet<Municipio> Municipio { get; set; }
        public virtual DbSet<Origen_Fabrica> Origen_Fabrica { get; set; }
        public virtual DbSet<Origen_Traspaso> Origen_Traspaso { get; set; }
        public virtual DbSet<OrigenEstado> OrigenEstado { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Promocion_Auto> Promocion_Auto { get; set; }
        public virtual DbSet<PromocionList> PromocionList { get; set; }
        public virtual DbSet<Referencias> Referencias { get; set; }
        public virtual DbSet<TipoEmpleado> TipoEmpleado { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<VentaAuto> VentaAuto { get; set; }
    }
}
