//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manten_Autopar
    {
        public int IdManten_Autopar { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> IdMantenimiento { get; set; }
        public Nullable<int> IdAutopartes { get; set; }
        public Nullable<int> Cantidad_Autopartes { get; set; }
    
        public virtual Autopartes Autopartes { get; set; }
        public virtual Mantenimiento Mantenimiento { get; set; }
    }
}
