//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Origen_Traspaso
    {
        public int IdOrigen_Traspaso { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<int> IdVendedor { get; set; }
        public Nullable<int> IdComprador { get; set; }
        public Nullable<int> IdConcesinaria { get; set; }
        public Nullable<int> IdAutomovil { get; set; }
        public Nullable<int> IdOrigenEstado { get; set; }
    
        public virtual Automovil Automovil { get; set; }
        public virtual Concesinaria Concesinaria { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual OrigenEstado OrigenEstado { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
