//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocion_Auto
    {
        public int IdPromocion_Auto { get; set; }
        public Nullable<int> IdAutoModelo { get; set; }
        public Nullable<int> IdPromocion { get; set; }
        public Nullable<int> IdConcesinaria { get; set; }
        public Nullable<bool> Vigente { get; set; }
    
        public virtual AutoModelo AutoModelo { get; set; }
        public virtual Concesinaria Concesinaria { get; set; }
        public virtual PromocionList PromocionList { get; set; }
    }
}
