//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referencias
    {
        public int IdReferencia { get; set; }
        public string Numero { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> TelCel { get; set; }
        public Nullable<int> IdCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
