//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaAuto_Promo
    {
        public int IdVentaAuto_Promo { get; set; }
        public Nullable<int> IdPromocion { get; set; }
        public Nullable<int> IdVentaAuto { get; set; }
    
        public virtual PromocionList PromocionList { get; set; }
        public virtual VentaAuto VentaAuto { get; set; }
    }
}
